spring.application.name=clickhouse-flatfile-app
server.port=8081
spring.datasource.url=jdbc:ch://localhost:8123/default
spring.datasource.username=testuser
spring.datasource.password=${CLICKHOUSE_PASSWORD}